### ISSUE TITLE
Drag+Drop/Dock of TreeView buggy

### ISSUE THREAD

**Issue by inoas** [atom/tree-view#1191]
### Prerequisites

* Platform mac OS X 10.12.6
* Atom 1.20.1

### Description

Drag + Drop only works after shrinking the window.

### Steps to Reproduce

1. Connect a 2nd Monitor and set it up to render a desktop on the right side
2. Maximize your Atom on your primary monitor
3. Drag + Drop the TreeView tab to the right: It will not work.

**Expected behavior:** Should work ;)

**Actual behavior:** Doesn't work ;-)

**Reproduces how often:** Always

### Versions

```
$ atom --version
Atom    : 1.21.0
Electron: 1.6.9
Chrome  : 56.0.2924.87
Node    : 7.4.0

$ apm --version
apm  1.18.5
npm  3.10.10
node 6.9.5 x64
python 2.7.10
git 2.13.5
```

### Additional Information

Works when shrinking the window.

*Worse than this however is that Packages -> Tree View -> Toggle Tree Side never works*
In conjunction it felt like I could not do anything about it (until I shrinked my window accidentially).

**Comment by rsese** [comment]
Thanks for opening a new issue @inoas :v:

> Drag + Drop the TreeView tab to the right: It will not work.

Just to confirm, does the dock handle not show up at all?  Or does it show up and dragging the tree view over it doesn't work?  

Also, based on your description it sounds like you're saying this only happens in the multiple monitor case?

**Comment by inoas** [comment]
- drag-handle does show up
- letting it go does nothing
- just tested single monitor now (evening) ... works

### Feedback
- should work when dragging on the tab bar, too
- Packages -> Tree View -> Toggle Tree Side really needs to work

**Comment by rsese** [comment]
Thanks for the details :+1:

> drag-handle does show up
> letting it go does nothing

Can you share a GIF or screencast of this behavior?

/cc https://github.com/atom/atom/issues/15728 where people have reported another issue with multiple monitors and the dock handles (in that case the handle isn't showing up).

> Packages -> Tree View -> Toggle Tree Side really needs to work

This was addressed in https://github.com/atom/tree-view/issues/1101#issuecomment-302303946 - the setting was removed but Atom still displays it since it's in your config file.

**Comment by inoas** [comment]
When I am back in my office I will try to replicate it and record that (not sure how yet, but I ll find some way)

>    Packages -> Tree View -> Toggle Tree Side really needs to work
> This was addressed in #1101 (comment) - the setting was removed but Atom still displays it since it's in your config file.

### Feedback on that:

- Bad that it was removed
- Bad that it still shows
- Bad that it cannot be toggled by hitting a key combo (like 3-4 control keys and d or p, see textmate)

**Comment by 50Wliu** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment https://github.com/atom/tree-view/issues/1191#issuecomment-336574965. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
